export enum FileUploadErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MAXIMUM_FILES_EXCEEDED = "MAXIMUM_FILES_EXCEEDED",
  UNSUPPORTED_MIME_TYPE = "UNSUPPORTED_MIME_TYPE",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  NOT_FOUND_OR_NOT_AUTHORIZED = "NOT_FOUND_OR_NOT_AUTHORIZED"
}